version: "3.9"
services:
  db:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"

  # app:
  #   container_name: chart-api
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - MONGO_DB_URI='mongodb://localhost:27017'
